name: Python CI/CD

on:
  push:
    branches:
      - main   # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main   # Trigger the workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'   # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest   # Replace with your testing command

      - name: Build and deploy (example)
        run: |
          python script.py   # Replace with your deployment command
